import xgboost as xgb
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix
from src.data.preprocess import LungCancerDataLoader

def run_final_test():
    # 1. Initialize loader and fetch the holdout test set
    loader = LungCancerDataLoader()
    X_test, y_test = loader.load_test_set()
    
    print(f"Loaded Test Set: {X_test.shape[0]} samples.")
    
    # 2. Load the best model generated by the training script
    try:
        model = xgb.XGBClassifier()
        model.load_model("best_xgb_lung_cancer.json")
        print("Model loaded successfully.\n")
    except Exception as e:
        print("Error loading model. Make sure to run train.py first.")
        return

    # 3. Predict on the unseen test set
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]
    
    # 4. Final Evaluation metrics
    print("--- Final Holdout Test Results ---")
    print(classification_report(y_test, y_pred))
    
    test_auc = roc_auc_score(y_test, y_pred_proba)
    print(f"Final Test ROC-AUC Score: {test_auc:.4f}")
    
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

if __name__ == "__main__":
    run_final_test()