import os

import xgboost as xgb
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix, accuracy_score, recall_score, f1_score, precision_score
import pandas as pd

def run_final_test():
    # 1. Initialize loader and fetch the holdout test set
    test_data = pd.read_csv("data/processed/test.csv")
    X_test = test_data.drop('LUNG_CANCER', axis=1)
    y_test = test_data['LUNG_CANCER']
    
    print(f"Loaded Test Set: {X_test.shape[0]} samples.")
    results = []
    
    # 2. Load the best model generated by the training script
    models = {
        "AUC": "src/models/XGBoost/saved/best_xgb_auc_lung_cancer.json",
        "Accuracy": "src/models/XGBoost/saved/best_xgb_accuracy_lung_cancer.json",
        "Precision": "src/models/XGBoost/saved/best_xgb_precision_lung_cancer.json",
        "Recall": "src/models/XGBoost/saved/best_xgb_recall_lung_cancer.json",
        "F1": "src/models/XGBoost/saved/best_xgb_f1_lung_cancer.json",
    }
    for metric, model_path in models.items():
        model = xgb.XGBClassifier()
        model.load_model(model_path)

        # 3. Predict on the unseen test set
        y_pred = model.predict(X_test)
        y_pred_proba = model.predict_proba(X_test)[:, 1]
        
        # 4. Final Evaluation metrics
        print("--- Final Holdout Test Results ---")
        print(classification_report(y_test, y_pred))

        test_auc = roc_auc_score(y_test, y_pred_proba)
        test_accuracy = accuracy_score(y_test, y_pred)
        test_f1 = f1_score(y_test, y_pred)
        test_recall = recall_score(y_test, y_pred)
        test_precision = precision_score(y_test, y_pred)
        print(f"Final Test ROC-AUC Score: {test_auc:.4f}")
        print(f"Final Test Accuracy Score: {test_accuracy:.4f}")
        print(f"Final Test F1 Score: {test_f1:.4f}")
        print(f"Final Test Recall Score: {test_recall:.4f}")

        print("\nConfusion Matrix:")
        print(confusion_matrix(y_test, y_pred))

        results.append({
            "Selected By": metric,
            "ROC-AUC": test_auc,
            "Accuracy": test_accuracy,
            "Precision": test_precision,
            "Recall": test_recall,
            "F1-Score": test_f1
        })

    xgb_test_results = pd.DataFrame(results)
    os.makedirs("src/models/XGBoost/trained_and_tested", exist_ok=True)
    xgb_test_results.to_csv(f"src/models/XGBoost/trained_and_tested/xgb_final_test_results.csv", index=False)

if __name__ == "__main__":
    run_final_test()